#!/usr/bin/env bash

export INDEX="2"
export BAO_DEMOS_FREERTOS=$BAO_DEMOS_WRKDIR_SRC/freertos$INDEX
make -C $BAO_DEMOS_FREERTOS PLATFORM=$PLATFORM $FREERTOS_PARAMS
cp $BAO_DEMOS_FREERTOS/build/$PLATFORM/freertos$INDEX.bin $BAO_DEMOS_WRKDIR_IMGS --verbose
